theme: minima

title: A Diary of IT Projects
author: cicero343
name: cicero343
description: My blog

baseurl: "/" # the subpath of your site, e.g. /blog

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sass-converter
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
    
navbar:
  - title: "My Gists"
    url: /gists/
  - title: "About me"
    url: /about/
  - title: "Posts"
    url: /posts/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock