theme: minima

title: A Diary of IT Projects
author: cicero343
name: cicero343
description: My blog

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sass-converter

navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: /projects/
  - title: "About me"
    url: /about/
