theme: minima

title: A Diary of IT Projects
author: cicero343
name: cicero343
description: My blog

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sass-converter

header_pages:
  - _pages/projects.md
  - _pages/about.md

