theme: minima

title: A Diary of IT Projects
author: cicero343
name: cicero343
description: My blog

baseurl: "/" # the subpath of your site, e.g. /blog

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sass-converter
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    
navbar:
  - title: "My Projects"
    url: /projects/
  - title: "About me"
    url: /about/
  - title: "All Posts"
    url: /posts/
  - title: "Dashboard"
    url: /dashboard/
  - title: "Cyber News"
    url: /cybernews/
  - title: "Terminal"
    url: /terminal/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

